---
title: "Group 44 - UCSB Domestic Grad Enrollment"
author: "Kirsten White & Trevor Maggart"
date: "11/14/2021"
output: html_document
---

```{r setup, include= TRUE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

```{r}
# Attach packages

library(tidyverse)
library(here)
```

```{r}
# Read in the data

ucsb_grad <- read_csv(here("data", "ucsb_grad_data.csv"))
```

```{r, fig.align='center'}
# Creating a column graph

ggplot(data = ucsb_grad, aes(x = year_abbr, y = domestic_enrollment)) + 
  geom_col(aes(fill = ethnicity),position = "fill") + # Sorting by proportion of ethnicity
  labs(x = "Year", 
       y = "Enrollment Percentage", 
       fill = "Ethnicity",
       title = "Distribution (%) of Student Ethnicity Across Enrollment Years at UCSB") +
  theme_minimal()
```
<center>**Figure 1.** Column graph showing the distribution of domestic graduate UCSB students based on ethnicity during the enrollment years 2008-2019. Columns are proportional and represent the percentage of students by ethnicity.</center>